-- ============================================================
-- Seed Data: All tables from MySQL (excluding users)
-- วางใน Supabase SQL Editor แล้วกด Run
-- ============================================================

INSERT INTO public.vehicles (id, project_affiliation, vehicle_name, license_plate, vehicle_image_path) OVERRIDING SYSTEM VALUE
VALUES
(6, 'โครงการวิจัยและพัฒนาจรวดหลายลำกล้องนำวิถี (D11A)', 'Surface-to-Air Missile', '54545', 'uploads/car_69140c10815c28.01691662.jpg'),
(7, 'โครงการวิจัยและพัฒนาจรวดหลายลำกล้องนำวิถี (D11A)', 'Surface', '456456', 'uploads/car_69140c3fb8f049.61045892.jpg');

INSERT INTO public.parts (id, part_id, quantity, standard_lifespan_days, part_name_en, part_name_th, part_text_en, part_text_th, part_image_path, part_video_path, part_sound_path) OVERRIDING SYSTEM VALUE
VALUES
(1, 'guest_info', 0, 365, 'R&D Project of Guided Multiple Launch Rocket System (D11A)', 'โครงการวิจัยและพัฒนาจรวดหลายลำกล้องนำวิถี (D11A)', 'D11A Project focuses on research and development of the Multi-Purpose Launcher capable of equipping with MLRS that has a firing range of 40–300 km. D11A project aims to serve the requirements of Royal Thai Army fire power, support the combat readiness level, and enhance the domestic defense industry to become self-sustaining in the future.\n\nThe Multi-Purpose Launcher developed by D11A is a TATRA T815-7TDR31 6x6.1R model. This vehicle has a physical dimension of 2.5m in width, 10m in length, 2.7m in height, with a weight of 29,000 kg, and is capable of staffing four crew members. Inside the vehicle is equipped with an automatic transmission and a fire control computer with an inertial reference system for the target, the vehicle location, and programming navigation for a guided rocket loaded in the cradle. The cradle is mounted on the turret, which is capable of elevating to 60 degrees above the horizon and has an azimuth of +/- 110 degrees in relation to the cabin of the vehicle. The vehicle can be reconfigured as needed to be best suited for the current mission at hand. The cradle can be equipped with three types of pods that house different rocket configurations. The available rockets are capable of firing at 40km, 150km, and 300 km in guided and unguided modes. The cradle can be rearmed at any instance allowing for an increase in combat readiness.', 'โครงการ D11A ได้มีการดำเนินการวิจัยและพัฒนาระบบต้นแบบรถฐานยิงจรวดหลายลำกล้องอเนกประสงค์ (Multi - Purpose Launcher) โดยมีเป้าหมายเพื่อตอบสนองความต้องการของกองทัพ สนับสนุนความพร้อมรบ และเพิ่มขีดความสามารถ ด้านอุตสาหกรรมป้องกันประเทศรวม ตลอดจนเป็นการเสริมสร้างนวัตกรรมและองค์ความรู้เพื่อผลิตยุทโธปกรณ์  ใช้งานได้เองภายในประเทศ นำไปสู่การพึ่งพาตนเองในอนาคต   รถฐานยิงจรวดหลายลำกล้องอเนกประสงค์ที่โครงการฯ ได้ดำเนินการวิจัยและพัฒนา เป็นรถ TATRA รุ่น T815-7TDR31 6x6.1R  มีความกว้าง 2.5 เมตร ยาว 10 เมตร สูง 2.7 เมตร น้ำหนักสูงสุด 29,000 กก. ระบบขับเคลื่อนเป็นแบบเกียร์อัตโนมัติ  สามารถบรรทุกกำลังพลได้สูงสุด 4 นาย  ภายในรถมีการติดตั้งระบบอำนวยการยิงแบบอัตโนมัติสำหรับช่วยในการระบุตำแหน่งเป้าหมาย รวมทั้งการระบุตำแหน่งของตัวรถ พร้อมทั้งยังสามารถส่งค่าพิกัดเป้าหมายให้ระบบนำร่องของจรวดแบบนำวิถีที่ถูกบรรจุอยู่ในระบบชุดแคร่ (Cradle)  โดยชุดแคร่ที่ถูกติดตั้งบน ระบบเครื่องยิง (Turret) จะสามารถทำระยะมุมยกได้สูงสุด 60 องศา และมุมส่ายสูงสุด  +/- 110 องศา การใช้งานรถมีความหยุ่นตามวัตุประสงค์ของภารกิจ โดยสามารถเปลี่ยนรวมท่อยิง (POD) ได้ 3 แบบ สามารถรองรับจรวดได้ทั้งนำวิถีและไม่นำวิถี ระยะยิงไกล 40 กม. 150 กม.  และ 300 กม. โดยสามารถเปลี่ยนชุดรวมท่อยิง (POD) บรรจุจรวดลูกใหม่ได้ทันทีหลังการยิง', 'uploads/part_690c5030896e07.12376037.jpg', 'no data', 'no data'),
(2, 'cabin', 9, 365, 'Cabin', 'ชุดหัวเก๋ง', 'The cabin section hosts the Launcher Operation Center where the crew can routinely perform operational activities. Cabin windows shielding are equipped to protect personnels and equipment inside. The cabin section is designed to be manned by 3 crew members i.e. a driver, operator, and the assigned maintainer. The followsing are the featured equipment inside the cabin: \n1. Launcher Mission Computer (LMC)\n2. GPS Receiver\n3. Operation Panel\n4. Emergency Switch\n5. Cabin Distribution Unit (CPDU)', 'หัวเก๋งทำหน้าที่เป้นศูนย์ปฎิบัติการของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจร(Launcher Operation Center) โดยการปฎิบัติปกติประจำ(Routine and Operational Activities) จะดำเนินการจากหัวเก๋ง มีการติดตั้งชุดป้องกันกระจกรถบรรทุก (Cabin Window Shielding) หัวเก๋งสามารถรองรับผู้ปฎิบัติจำนวน 3 นาย ประกอบด้วยพลขับจำนวน 1 นาย ผู้ปฎิบัติจำนวน 1 นาย และพลประจำรถจำนวน 1 นาย ภายในหัวเก๋งมีการติดตั้งอุปกรณ์ดังต่อไปนี้\r\n1.คอมพิวเตอร์ควบคุมการยิง(Launcher Mission Computer : LMC)\r\n2.เครื่องรับสัญญาณของระบบกำหนดตำแหน่ง(GPS Receiver)\r\n3.แผงการควบคุมการยิง(Operation Panel)\r\n4.สวิตช์ปิดระบบกรณีฉุกเฉิน(Emergency Switch)\r\n5.ชุดจ่ายไฟฟ้าในห้องโดยสาร(Cabin Distribution Unit, CPDU)', 'uploads/part_690c4fe8998967.54669490.jpg', 'no data', 'no data'),
(3, 'windows_guard', 48, 365, 'Windows Guard', 'ชุดป้องกันกระจก', 'Windows guard are designed to protect the crew from shrapnel and debris impact during rocket launching sequence. These guards are mount on the front windows and the side window. All windows guards are made from aluminum.', 'ทำจากอะลูมิเนียม (Aluminum) มีหน้าที่ป้องกันพลประจำรถจากกระสุน (Shrapnel) และเศษวัสดุ (Flying Parts) ที่มาชนกระจกขณะทำการยิงและการปล่อยจรวด โดยประกอบด้วย ชุดป้องกันกระจกหน้า (Front Window Shield) และชุดป้องกันกระจกข้าง (Side Window Shield)', 'uploads/part_690c4fe499ed46.46400307.jpg', 'no data', 'no data'),
(4, 'chassis', 50, 365, 'Chassis', 'แชสซิส', 'Main frame of the launcher \nWheelbase: 4,090 + 1450 mm\nMaximum payload weight 18,760 kg\nMaximum gross weight 29,000 kg', 'เป็นโครงสร้างหลักของตัวรถ ฐานล้อ 4,090 + 1,450 มม.\nน้ำหนักบรรทุกสูงสุด 18,760 กก.\nน้ำหนักรถสูงสุด 29,000 กก.', 'uploads/part_690c501f591e29.71602709.jpg', 'no data', 'no data'),
(5, 'engine_specification', 49, 365, 'Engine Specification', 'คุณลักษณะเครืองยนต์', 'V8 diesel piston engine TATRA T3C-928.90', 'เครื่องยนต์ดีเซลรุ่น TATRA T3C-928.90 มีลูกสูบ 8 สูบ จัดเรียงแบบรูปตัว V', 'uploads/part_690c4efa324e96.49952572.jpg', 'no data', 'no data'),
(6, 'tires', 47, 365, 'Tires', 'ล้อ', 'Run Flat tires', 'ยางแบบ Run Flat', 'uploads/part_690ad4552281f7.61768363.png', 'ืno data', 'ืno data'),
(7, 'suspension', 48, 365, 'Suspension', 'ช่วงล่าง', ' ', 'Independent suspension ระบบขับเคลื่อน 6x6 มีระบบ Differential Lock', 'uploads/part_690c4f00a16b23.97573682.jpg', 'no data\r\n', 'no data'),
(8, 'battery', 50, 365, 'Battery', 'แบตเตอรี่รถ+อัลเตอเนเตอร์', 'Launcher battery is a default 12 volt from the launcher platform manufacturer. The battery is mounted on the left side of the rocket pod. The battery is used to power the electrical components of launcher platform and engines. The alternator in the engine automatically charges the battery at 24VDC when the engine is operating', 'รถบรรทุกมีแบตเตอรี่ขนาด 12 โวลต์ (V) ซึ่งเป็นแบตเตอรี่ดั้งเดิมที่ถูกติดตั้งมาจากผู้ผลิตรถบรรทุก โดยแบตเตอรี่รถบรรทุกติดตั้งทางด้านซ้ายของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจรและใช้ในการจ่ายกำลังไฟฟ้าไปที่ชุดอุปกรณ์ไฟฟ้าของรถบรรทุกและเครื่องยนต์ แบตเตอรี่รถบรรทุกถูกชาร์จโดยอัลเตอเนเตอร์และต่อแบบอนุกรมเพื่อจ่ายไฟฟ้ากระแสตรงขนาด 24 โวลต์ (VDC) และชาร์จแบตเตอรี่ระบบ (System Batteries)', 'uploads/part_690c5027846f43.13825083.jpg', 'no data', 'no data'),
(9, 'sub_chassis', 50, 365, 'Sub-Chessis', 'โครงสร้างย่อย', 'A sub chassis is a part of structure that connects between a platform and a 6x6 truck chassis. The connection is done by rod connector which is a flexible connection type and a rid connection type. Rigid connection is permanent and cannot be removed for field maintenance. ', 'โครงสร้างย่ยเป็นส่วนที่เชื่อมต่อกับชุดโครงสร้าง(Platform) และแชสซิสรถบรรทุก 6x6 (6x6 Truck Chassis) โครงสร้างย่อยติดตั้งบนแชสซีสรถบรรทุกด้วยการเชื่อมต่อแบบการสวมแก (Rod Connector) ซึ่งเป็นการยึดแบบยืดหยุน (Flexible Connection) และการเชื่อมต่อแบบแผ่นเหล็กซึ่งเป็นการยึดแบบแข็งแรง (Rigid Connection) ซึ่งการยึดเป็นการเชื่อมต่อแบบถาวรและไม่สามารถบำรุงรักษาภาคสนามได้(Field Serviceable)', 'uploads/part_690c5034d5cbc9.49568108.jpg', 'no data', 'no data'),
(10, 'platform', 50, 365, 'Platform', 'ชุดโครงสร้าง', 'Platform is the main structure of this launch vehicle. The turret and cradle are mounted on top of the platform. The platform is positioned behind the cabin and on top of the Sub chassis. Platform is made from “iron” and designed to support the subassemblies of rocket launcher.', 'ชุดโครงสร้างเป็นส่วนประกอบหลัก ด้านบนของชุดโครงสร้างนั้นติดตั้งชุดเครื่องยิง (Terret) และชุดแคร่ (Cradle) ซึ่งชุดโครงสร้างถูกติดตั้งด้านหลังของหัวเก๋งและอยู่บนโครงสร้างย่อย (Sub-Chassis) ชุดโครงสร้างทำมาจากเหล็กและรองรับส่วนประกอบย่อยต่างๆ (Subassembies) ของฐานปล่อยจรวดหลายลำกล้อง', 'uploads/part_690c4ffd075d06.20257118.jpg', 'no data', 'no data'),
(11, 'stabilizer', 50, 365, 'Stabilizers', 'เท้าช้าง', 'The launcher is equipped with 4 stabilizers. Stabilizer is designed to damped the vibration and movement of launcher. Each stabilizer is powered by hydraulic and compose of \n- Lock and clamp to ensure the stabilizer is securely in stowed position when launcher is on the move.\n- Stabilizer pad to distribute the weight of launcher and leveling the platform.\n- Folding arm to extend and retract the stabilizer', 'ฐานปล่อยจรวดหลายลำกล้องเนกประสงค์อัตตราจรติดตั้งเท้าช้างจำนวน 4 ชุด ทำงานด้วยระบบไฮดอรลิค ซึ่งเท้าช้างจะใช้สำหรับป้องกันการสั่นสะเทือน (Flexible Effect) ของระบบการสั่นสะเทือนรถบรรทุก (Truck Suspension) โดยเท้าช้างแต่ละชุดประกอบด้วยส่วนประกอบต่อไปนี้\r\n-กลไกการยึด (Lock) และแคลมป์ (Clamp) เพื่อใช้สำหรับยึดตรึงเท้าช้างในตำแหน่งที่ถูกพับเก็บเพื่อป้องกันการเปิดขณะเคลื่อน\r\n-แผ่นกระจายแรงของเท้าช้าง เพื่อใช้กระจายแรงดันบนพื้นและการปรับคงที่ระดับ (Stabilization)\r\n-กระบอกสูบเท้าช้าง (Stabilizer Pistons) เป็นกระบอกไฮดอรลิคเพื่อใช้ยืดและหดเท้าช้าง\r\n-แขนพับ (Folding Arm)', 'uploads/part_690c501af2e675.52197114.jpg', 'no data', 'no data'),
(12, 'equipment_compartment', 94, 365, 'Equipment Comparment', 'ห้องสำหรับอุปกรณ์', 'Equipment compartment store the tool and special equipment for the crew. These equipment allows an uninterrupted operation and maintenance of launcher. The equipment compartment is located on the top left section of the platform.', 'ห้องสำหรับอุปกรณ์ใช้สำหรับเก็บเครื่องมือของพลขับและอุปกรณ์พิเศษสำหรับการปฎิบัติงานและบำรุงรักษาฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจร ห้องสำหรับอุปกรณ์ติดตั้งอยู่บนด้านซ้ายของชุดโครงสร้าง(Platform)', 'uploads/part_690c50163e4ac8.29714044.jpg', 'no data', 'no data'),
(13, 'turret', 1, 365, 'Turret', 'ชุดเครื่องยิง', 'The turret is mounted on top of the platform. The turret has a range of motion in azimuth of ±110 degrees and is powered by normally by hydraulic and hand crack in an emergency situation. Inside the turret is equipped with Transverse Hydraulic Motor and Gear, Hydraulic Valve and Manifolds, Hydraulic Tube, Transverse Limiters, No Firing Zone Micro Switches, Main Power Distribution Unit (MPDU), Electric Hydraulic Unit (EHU), Fire Control Unit (FCU), Servo Control Unit (SCU), and Ethernet Switches.', 'ชุดเครื่องยิงติดตั้งอยู่บนชุดโครงสร้าง (Platform) และสามารถหมุนทางข้างด้วยระบบไฮดรอลิคและด้วยมือได้ ±110 องศา โดยมีชุดอุปกรณ์หมุนเวียนติดตั้งอยู่ภายใน ได้แก่ มอเตอร์ไฮโดรลิคและชุดเฟืองขับสำหรับการเคลื่อนที่ทางข้าง (Transverse Hydraulic Motor and Gear) วาล์วและฐานวาล์วไฮโดรลิค (Hydraulic Valve and Manifolds) ท่อส่งไฮโดรลิค (Hydraulic Tube) ลิมิเตอร์ทางข้าง (Transverse Limiters) สวิทช์แบบไมโครพื้นที่ห้ามยิง (No Firing Zone Micro Switches) ชุดการจ่ายไฟหลัก (Main Power Distribution Unit, MPDU) และชุดจ่ายไฟฟ้าในห้องโดยสาร (Cabin Distribution Unit, CPDU) ชุดไฟฟ้าควบคุมไฮโดรลิค (Electric Hydraulic Unit, EHU) ปั๊มมือสำหรับยก (Elevation Manual  Pump) ชุดควบคุมการยิง (Fire Control Unit, FCU) ชุดควบคุมเซอร์โว (Servo Control Unit, SCU) ชุดสวิทช์ Ethernet (Ethernet Switches)  ', 'uploads/part_690c4ff11f3700.25216401.jpg', 'no data', 'no data'),
(14, 'cradle_and_turret', 50, 365, 'Cradle and Turret', 'ชุดแคร่และชุดเครื่องยิง', 'The cradle was designed to support and elevate rocket pod at a different size. The cradle is powered by Hydraulic Elevation Piston which connected between the turret and cradle. The piston is controlled by SCU or manual crank handle. The pod has the elevation range from 0 – 75 degrees. There are 8 pistons connecting between the pod and turret. Cradles also composed of \n1. Fire control section\n2. 2 Fire Relay Unit (FRU)\n3. 2 Switching Unit (SU)\n4. Test unit (TU)\n5.  Hydraulic section\n6.  Elevation pistons\n7.  Oil booster \n8.  Navigation section\n9.  Launch Navigation System (LNS)\n\nThe turret is mounted on top of the platform. The turret has a range of motion in azimuth of ±110 degrees and is powered by normally by hydraulic and hand crack in an emergency situation. Inside the turret is equipped with Transverse Hydraulic Motor and Gear, Hydraulic Valve and Manifolds, Hydraulic Tube, Transverse Limiters, No Firing Zone Micro Switches, Main Power Distribution Unit (MPDU), Electric Hydraulic Unit (EHU), Fire Control Unit (FCU), Servo Control Unit (SCU), and Ethernet Switches.', 'ชุดแคร่ทำหน้าที่รองรับและยกชุดรวมท่อยิง (POD) ขนาดต่างๆ ไปยังความสูงที่ต้องการปล่อยจรวจระหว่างภารกิจการยิง ชุดแคร่ยกขึ้นได้ด้วยกระบอกสูบไฮดรอลิก (Hydraulic Elevation Poston) ซึ่งเชื่อมต่อระหว่างชุดเครื่องยิง (Turret) และชุดแคร่ (Cradle) และควบคุมด้วยชุดควบคุมเซอร์ไว(SCU) หรือด้วยมือมนช่วงระหว่างมุม 0 องศา - 75 องศา ในการยึดชุดรวมท่อยิงเข้ากับชุดแคร่นั้นจะใช้กระบอกสูบทั้งหมดจำนวน 8 ตัว โดยชุดแคร่ประกอบด้วยส่วนประกอบดังต่อไปนี้\n      1. ส่วนของระบบการยิง\n         - ชุดรีเลย์การยิง (Fire Relay Unit, FRU) จำนวน 2 ชุด\n         - ชุดการปิดเปิดวงจร (Switching Unit, SU) จำนวน 2 ชุด\n         - ชุดทดสอบ (Test Unit, TU)\n      2. ส่วนของระบบไฮดรอลิค\n        - กระบอกสูบสำหรับการยก (Elevation Pistons)\n        - อุปกรณ์เพิ่มแรงดันน้ำมัน (Oil Booster)\n      3. ส่วนของระบบนำทาง\n        - ระบบนำทางฐานปล่องจรวดฯ (Luanch Navigation System, LNS)\n\nชุดเครื่องยิงติดตั้งอยู่บนชุดโครงสร้าง (Platform) และสามารถหมุนทางข้างด้วยระบบไฮดรอลิคและด้วยมือได้ ±110 องศา โดยมีชุดอุปกรณ์หมุนเวียนติดตั้งอยู่ภายใน ได้แก่ มอเตอร์ไฮโดรลิคและชุดเฟืองขับสำหรับการเคลื่อนที่ทางข้าง (Transverse Hydraulic Motor and Gear) วาล์วและฐานวาล์วไฮโดรลิค (Hydraulic Valve and Manifolds) ท่อส่งไฮโดรลิค (Hydraulic Tube) ลิมิเตอร์ทางข้าง (Transverse Limiters) สวิทช์แบบไมโครพื้นที่ห้ามยิง (No Firing Zone Micro Switches) ชุดการจ่ายไฟหลัก (Main Power Distribution Unit, MPDU) และชุดจ่ายไฟฟ้าในห้องโดยสาร (Cabin Distribution Unit, CPDU) ชุดไฟฟ้าควบคุมไฮโดรลิค (Electric Hydraulic Unit, EHU) ปั๊มมือสำหรับยก (Elevation Manual  Pump) ชุดควบคุมการยิง (Fire Control Unit, FCU) ชุดควบคุมเซอร์โว (Servo Control Unit, SCU) ชุดสวิทช์ Ethernet (Ethernet Switches)  ', 'uploads/part_690c4fecc57c67.01465653.jpg', 'no data', 'no data'),
(15, 'hydraulic_system', 50, 365, 'Hydraulic System', 'ระบบไฮดรอลิค', 'A hydraulic system delivers a highly pressurized hydraulic fluid to provide motion for various systems on the launcher vehicle. A launcher engine or the electric pump can be used to pressurize the hydraulic system. Crew can operate the hydraulic system via the hydraulic panel and monitor the status of the system via hydraulic pressure panel. An electric hydraulic pump is a standby pressurized source which is powered by the battery of the launcher. The manual hand crank is also available in case of total hydraulic system failure.', 'ระบบไฮดรอลิคเป็นระบบที่ทำหน้าที่ส่งน้ำมันไฮดรอลิคซึ่งถูกทำให้มีแรงดันสูงเพื่อทำให้ระบบไฮดรอลิคของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจรทำงาน ระบบไฮดรอลิคสามารถทำงานได้โดยใช้กำลังจากรถบรรทุกและยังสามารถทำงานได้อย่างอิสระด้วยปั๊มไฟฟ้า ผู้ปฏิบัติสามารถควบคุมระบบไฮดรอลิคจากแผงควบคุมไฮดรอลิค (Hydraulic Panel) และตรวจติดตามความดันได้จากแผงวัดความดันไฮดรอลิค (Hydraulic Pressure Panel) ระบบไฮดรอลิคมีปั๊มไฟฟ้าเป็นระบบสำรองซึ่งสามารถทำงานได้โดยการจ่ายไฟจากแบคเตอรี่ของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจรและมีตัวเลือกสนับสนุนสำหรับการทำงานด้วยมือต่างๆ', 'uploads/part_690c500ca629a1.47935896.jpg', 'no data', 'no data'),
(16, 'launcher_battery', 50, 365, 'Launcher Battery', 'แบตเตอรี่ฐานปล่อยจรวด', 'The battery system provides 24 VDC to the launcher various electrical systems. The system consists of 4 battery in total. Two batteies are used to support main launcher vehicle system and additional two are dedicate to the firing system. The batteries are mounted on the right side of the vehicle next to the hydraulic manual control handle. The batteries are connected in series circuit to provided a combined 24VDC. The dedicated firing system batteries can be charged via main battery. However, firing system batteries can\'t be used to charged the main battery. ', 'ระบบแบตเตอรี่จ่ายไฟกระแสตรงขนาด 24 โวลต์ (VDC) ให้หับทุกส่วนประกอบของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจร โดยจะประกอบไปด้วยแบตเตอรี่ทั้งหมดจำนาน 4 ลูก คือ แบตเตอรี่ดั้งเดิมที่ถูกติดตั้งมาจากผู้ผลิตรถบรรทุกจำนวน 2 ลูก และ แบตเตอรี่เพิ่มเติมจำนวน 2 ลูก สำหรับยิง (Firing System) โดยแบตเตอรี่จะถูกติดตั้งทางขวามือของตัวรถถัดจากชุดควบคุมไฮดอรลิคด้วยมือ (Hydraulic Manual Control) ซึ่งแบตเตอรี่จะถูกต่อแบบอนุกรมและจ่ายไฟกระแสตรงขนาด 24 โวลต์ ถ้าจำเป็นแบตเตอรี่ระบบจะสามารถถูกชา์จโดยแบตเตอรี่รถบรรทุกได้ แต่แบตเตอรี่ระบบจะไม่สามารถชาร์จให้แบตเตอรี่รถบรรทุกได้ ', 'uploads/part_690c50235024c7.87317590.jpg', 'no data', 'no data'),
(17, 'fire_control_panel', 50, 365, 'Fire Control Panel', 'แผงควบคุมการยิง', 'Operational Panel is used to coordinate between fire control system and other systems based on the state selector switch position. Operational panel has \n- State Selector Switch\n- Fire Button\n- Arm Switch ', 'ระบบควบคุมการยิงประกอบด้วยชุดอเล็คโทรนิกส์(Electronics) ที่มีความสำคัญต่อการทำงานของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตรจรระหว่างการปฎิบัติภารกิจการยิงและระหว่างการดำเนินการที่ไม่เกี่ยวข้องกับการปฎิบัติการยิง(Non-Operational Activities) ระบบควบคุมการยิงมีส่วนประกอบดังต่อไปนี้\r\n1.แผงควบคุมการทำงาน (Operation Panel, OP)\r\n2.คอมพิวเตอร์ควบคุมการยิง(Launcher Mission Computer : LMC)\r\n3.ชุดควบคุมการยิง(Fire Control Unit, FCU)\r\n4.ชุดควบคุมเซอร์โว(Servo Control Unit, SCU)\r\n5.ชุดควบคุมระบบไฟฟ้า(Electrical Box) มีส่วนประกอบดังต่อไปนี้\r\n   5.1.ชุดรีเลย์จุดจรวด(Fire Relay Unit, FRU)\r\n   5.2.ชุดการปิดเปิดวงจร(Switching Unit, SU)\r\n   5.3.ชุดทดสอบ(Test Unit, TU)\r\n6.สวิทช์ Ethernet (Ethernet Switch)\r\n7.เครื่องรับสัญญาณของระบบกำหนดตำแหน่ง(GPS Receiver)\r\n8.ชุดรวมท่อยิง(PODS)\r\n4.5.1 แผงควบคุมการทำงาน(Operation Panel) แผงควบคุมการทำงานมีหน้าที่ทำให้ระบบย่อยของระบบควบคุมการยิงทำงานและสื่อสารกันซึ่งขึ้นอยู่กับสถานะที่เลือก แผงควบคุมการทำงานติดตั้งภายในห้องโดยสารและประกอบไปด้วย 3 ส่วนหลักดังนี้\r\n- สวิทช์เลือกสถานะ(State Selector) \r\n- ปุ่มยิงจรวด(Fire Button)\r\n- สวิทช์ปลดนิรภัยจุดจรวด(Arm Switch)', 'uploads/part_690c502c23a5c4.07361681.jpg', 'no data', 'no data'),
(18, 'launcher_mission_computer', 39, 365, 'Launcher Mission Computer', 'คอมพิวเตอร์ควบคุมการยิง', 'Launcher mission computer (LMC) is the Panasonic CF-19 whcih has a high durability rating. LMC is equipped inside the cabin and mounted on the support platform. This platform is designed properly to secured LMC in position, support a charging station, and provide interface ports toward various systems related to firing operation. LMC has a fire control and operation software installed which allowed the crew to perform the following task \n- Planning and Activating a Fire Mission, \n- Built-in Test(BIT)\n- Mission Feasibility Check \n- Ammunition Inventory Check\n- Storing and update database of each pod \n- Fire Relay Unit and Switching Unit test result', 'คอมพิวเตอร์ควบคุมการยิงเป็นคอมพิวเตอร์รุ่น Panasonic CF-19 ที่มีความแข็งแรงทนทาน และติดตั้งภายในห้องโดยสาร โดยติดตั้งเข้ากับชุดรองรับเฉพาะที่สามารถรักษาเสถียรภาพของคอมพิวเตอร์ควบคุมการยิง ชาร์จแบตเตอรี่ของตัวเครื่อง และเชื่อมต่อกับส่วนประกอบที่เกี่ยวข้องกับระบบยิงต่างๆ โดยได้รับการติดตั้งซอฟแวร์สำหรับควบคุมและปฏิบัติภารกิจการยิงและมีส่วนต่อประสานกับผู้ปฏิบัติ (Operator Interface) เพื่อทำการปฏิบัติภารกิจ ได้แก่ การวางแผนและปฏิบัติภารกิจยิง (Planning and Activating a Fire Mission) การติดตามการตั้งมุมทิศและมุมยิงของฐานปล่อยจรวดฯ เชื่อมต่อกับฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจร การทดสอบภายใน (Built-in Test, BIT) เพื่อติดตามการทำงานชุดอุปกรณ์ของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจร การทดสอบความเป็นไปได้ของภารกิจ (Mission Feasibility Check) การตรวจสอบจรวดคงคลัง (Ammunition Inventory)\r\nนอกจากนี้ คอมพิวเตอร์ควบคุมการยิงยังทำหน้าที่เก็บรักษาและอัพเดทฐานข้อมูล (Database) สำหรับข้อมูลในแต่ละชุดท่อยิงแยกจากกัน ได้แก่ ชนิดของจรวดที่บรรจุในชุดรวมท่อยิง การมีหรือไม่มีลูกจรวด ผลการทดสอบชุดรีเลย์จุดจรวด (Fire Relay Unit, FRU) และ ผลการทดสอบชุดการเปิดปิดวงจร (Switching Unit, SU)', 'uploads/part_690c4ef52550c0.89041880.jpg', 'no data', 'no data'),
(19, 'fire_control_system', 50, 365, 'Fire Control System', 'ชุดควบคุมการยิง', 'Fire control system is composed mainly of electronic units. This system is crucial to the operational and non-operational activiteis of the launhcer vehcle. The fire control system is made up of\n1. Operational Panel (OP)\n2. Launcher Mission Computer (LMC)\n3. Fire Control Unit (FCU)\n4. Servo Control Unit (SCU)\n5. Electrical box which contain \n        5.1 Fire Relay Unit (FRU)\n        5.2 Switching Unit (SU)\n        5.3 Test Unit (TU)\n6. Ethernet Switch\n7. GPS Receiver \n9. PODS', 'ระบบควบคุมการยิงประกอบด้วยชุดอิเล็คทรอนิกส์ (Electronic) ที่มีความสำคัญต่อการทำงานของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจรระหว่างการปฏิบัติภารกิจการยิงและระหว่างการดำเนินการที่ไม่เกี่ยวข้องกับการปฏิบัติการยิง (Non-Operational Activities) ระบบควบคุมการยิงมีส่วนประกอบดังต่อไปนี้\r\n     - แผงควบคุมการทำงาน (Operation Panel, OP)\r\n     - คอมพิวเตอร์ควบคุมการยิง (Launcher Mission Computer, LMC)\r\n     - ชุดควบคุมการยิง (Fire Control Unit, FCU)\r\n     - ชุดควบคุมเซอร์โว (Servo Control Unit, SCU)\r\n     - ชุดควบคุมระบบไฟฟ้า (Electrical Box)\r\n        - ชุดรีเลย์จุดจรวด (Fire Relay Unit, FRU)\r\n        - ชุดการปิดเปิดวงจร (Switching Unit, SU)\r\n        - ชุดทดสอบ (Test Unit, TU)\r\n     - สวิทซ์ Ethernet (Ethernet Switch)\r\n     - เครื่องรับสัญญาณของระบบกำหนดตำแหน่ง (GPS Receiver)\r\n     - ชุดรวมท่อยิง (PODs)', 'uploads/part_690c4f055bf793.02952676.jpg', 'no data', 'no data'),
(20, 'inertial_navigation_system', 50, 365, 'Inertial Navigation System, INS', 'ระบบนำทางด้วยแรงเฉื่อย', 'no data', 'ระบบนำทางด้วยแรงเฉื่อยติดตั้งด้านบนแคร่ (Cradle) ระหว่างชุดรวมท่อยิงและส่งข้อมูลการนำทางและแรงเฉื่อยให้กับฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจรซึ่งจำเป็นสำหรับการคำนวณหาพิกัดของตัวเองเทียบกับทิศเหนือจริง (Alignment Calculations อุปกรณ์นำทางด้วยแรงเฉื่อยอยู่ด้านบนของชุดแคร่ระหว่างชุดรวมท่อยิงและถูกปิดโดยฝาครอบด้วยสกรูขนาด 13\"', 'uploads/part_690c50072ebd53.72054747.jpg', 'no data', 'no data'),
(21, 'global_positioning_sytem', 50, 365, 'Global Positioning Sytem, GPS', 'ระบบกำหนดตำแหน่ง (Global Positioning System, GPS)', 'Global Positioning System (GPS) is a highly accurate launcher self identify positioning system that provide its own latitude and longitude information. The GPS consists of the antena which mounted on the top of the cabin and wired directly to the processing unit. The laucnher current position will be continuously update allowing for an uninterrupted firing operation.', 'ระบบกำหนดตำแหน่งเป็นอุปกรณ์ที่ระบุตำแหน่งของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์อัตราจรด้วยข้อมูลพิกัดของฐานปล่อยจรวดฯ ที่มีความแม่นยำ เสาส่งสัญญานอุปกรณ์กำหนดตำแหน่ง (Antenna) จะติดตั้งอยู่ด้านบนของหัวเก๋งและเชื่อมต่อกับอุปกรณ์กำหนดตำแหน่ง โดยอุปกรณ์กำหนดตำแหน่งจะระบุและอัพเดตตำแหน่งของฐานปล่อยจรวดหลายลำกล้องอเนกประสงค์ในพื้นที่เปิดโดยที่ไม่มีการรบกวนสัญญานของดาวเทียม', 'uploads/part_690c4ff8a53c24.75249998.jpg', 'no data', 'no data'),
(22, 'emergency_switch', 48, 365, 'Emergency Switch', 'สวิตช์ฉุกเฉิน', 'Emergency Switch', 'สวิตช์ฉุกเฉิน', 'uploads/part_690c50117c1372.37504433.jpg', 'no data', 'no data'),
(23, 'fuel_tank', 47, 365, 'Fuel Tank', 'ถังน้ำมัน', 'Fuel Tank', 'ถังน้ำมัน', 'uploads/part_690c4ff4ca7193.61808168.jpg', 'no data', 'no data'),
(25, 'catime', 20, 5, '', 'อะไหล่แมว', '', '', 'uploads/part_690c52639772c5.74379794.webp', '', '');

INSERT INTO public.posts (id, title, featured_image_path, content, author_id, created_at) OVERRIDING SYSTEM VALUE
VALUES
(1, 'แจ้งเพื่อทราบ: รายงานผลการทดสอบระบบบริหารจัดการยานพาหนะ D11A เฟส 1.2', 'uploads/post_69129e29d671e0.74055660.jpg', 'เรียน ผู้ดูแลระบบและผู้ใช้งานทุกท่าน,\r\n\r\nข้อความนี้จัดทำขึ้นเพื่อเป็น ข้อมูลทดสอบระบบการโพสต์ประกาศ (Post Content Stress Test) โดยมีวัตถุประสงค์หลักในการประเมินความสามารถในการแสดงผลของเนื้อหาจำนวนมากและข้อความที่มีรูปแบบพิเศษ (เช่น การใช้รายการ, การจัดรูปแบบย่อหน้า) ในสภาพแวดล้อมจริงของระบบ โปรดละเว้นการดำเนินการใด ๆ ตามเนื้อหานี้ เนื่องจากไม่ใช่ประกาศจริง\r\n\r\n1. ผลการประเมินเบื้องต้น (Phase 1.2 Evaluation Summary):\r\n\r\nความเสถียรของฐานข้อมูล: การเชื่อมต่อและการดึงข้อมูลผ่าน PHP/SQL มีความเสถียรดีเยี่ยม (Status: Stable)\r\n\r\nการแสดงผลบนหน้าจอ: Layout โดยรวมของหน้า Admin และหน้าผู้ใช้ ยังคงรักษา ธีมทหาร (Military Theme) ได้อย่างสมบูรณ์แบบตามที่กำหนดไว้\r\n\r\nการจัดการสิทธิ์: ระบบยืนยันการกรองข้อมูลตามสังกัดโครงการ (affiliation) ของ Admin ในส่วนต่าง ๆ เช่น การจัดการผู้ใช้งาน, ยานพาหนะ, คำร้องซ่อมบำรุง, และ ใบเบิกอะไหล่ ได้อย่างถูกต้อง\r\n\r\n2. ข้อสังเกตสำหรับการพัฒนาในอนาคต:\r\n\r\nเพิ่มความละเอียดในการบันทึก Log การเข้าถึงสำหรับผู้ดูแลระบบระดับสูง (Super Admin)\r\n\r\nปรับปรุงความเร็วในการโหลดตารางที่มีข้อมูลขนาดใหญ่ (Optimization for Polling Data)\r\n\r\nทดสอบการลบไฟล์ที่แนบมากับคำร้องแจ้งซ่อมซ้ำอีกครั้ง เพื่อยืนยันว่า Path ในเซิร์ฟเวอร์ถูกลบอย่างสมบูรณ์\r\n\r\nย้ำเตือนอีกครั้ง: ห้ามดำเนินการใด ๆ ตามเนื้อหานี้ ข้อมูลข้างต้นเป็นเพียงชุดข้อมูลจำลองเพื่อใช้ในการทดสอบประสิทธิภาพสูงสุดของช่องข้อมูลประกาศของระบบ D11A เท่านั้น\r\n\r\nลงชื่อ: ทีมพัฒนาและทดสอบระบบบริหารจัดการยานพาหนะ วันที่: 11 พฤศจิกายน 2568 รหัสการทดสอบ: TST_11112568_LGTX', NULL, '2025-11-11 02:23:37');

INSERT INTO public.general_requests (id, user_id, request_type, subject, details, status, created_at, admin_notes) OVERRIDING SYSTEM VALUE
VALUES
(1, NULL, 'contact_form', 'ddd', 'ddd', 'rejected', '2025-11-11 02:37:38', 'sss'),
,
(3, 13, 'ขอลางาน', 'ลางาน', '-----', 'rejected', '2025-11-12 04:12:34', '----');

-- Reset sequences
SELECT setval('public.vehicles_id_seq', (SELECT MAX(id) FROM public.vehicles));
SELECT setval('public.parts_id_seq', (SELECT MAX(id) FROM public.parts));
SELECT setval('public.posts_id_seq', (SELECT MAX(id) FROM public.posts));
SELECT setval('public.general_requests_id_seq', (SELECT MAX(id) FROM public.general_requests));
